### ISSUE TITLE
Kernel Security Check

### ISSUE THREAD

**Issue by gergew452** [dumbasPL/fumo_loader#11]
Hello, I have collected everything, but when injected into the process Game.exe I get a blue screen
![image](https://github.com/user-attachments/assets/a4e7b2d8-f65f-4202-855d-64a71972eaf8)

**Comment by gergew452** [comment]
if you use ready-made exe that you have, then there is no such thing

**Comment by dumbasPL** [comment]
fixed in https://github.com/dumbasPL/fumo_loader/releases/tag/v1.0.3

if this is still an issue, please open a new one
