### ISSUE TITLE
nothing happens when injecting to roblox(usermode anticheat).

### ISSUE THREAD

**Issue by wxzex** [dumbasPL/fumo_loader#3]
https://github.com/dumbasPL/fumo_loader/assets/130822426/7f35a711-e4de-4e95-8a0b-72c962a6c281

**Comment by dumbasPL** [comment]
remove line 6 from `src\driver\CMakeLists.txt` `target_compile_definitions(fumo_drv PRIVATE -DNO_FUMO_DRIVER_DEBUG)` and recompile

use https://learn.microsoft.com/en-us/sysinternals/downloads/debugview to view the logs (make sure to enable kernel logging)

and send logs and/or video

**Comment by dumbasPL** [comment]
not sure what's blocking it but it might be related to the sellcode run inside the process. Currently, it uses `LdrLoadDll`, `LdrGetProcedureAddress`, and `RtlAnsiStringToUnicodeString` to resolve imports. So the AC is either blocking that or somehow preventing the APC from being dispatched. I don't feel like downloading this shit game so you're on your own. If you manage to find out what's blocking it let me know. One way would be to map all the dependencies separately alongside your DLL, but that would require a bit of work in the loader. The first thing I would try is mapping a DLL with no dependencies or only with ones already present in the process.

If I had to guess I would say they are checking the return addresses of calls to the windows loader functions.

**Comment by dumbasPL** [comment]
> ![image](https://private-user-images.githubusercontent.com/130822426/303942140-5a9e0686-4c28-4d55-9cfa-a24dc7dcd7c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2OTgwNjcsIm5iZiI6MTcwNzY5Nzc2NywicGF0aCI6Ii8xMzA4MjI0MjYvMzAzOTQyMTQwLTVhOWUwNjg2LTRjMjgtNGQ1NS05Y2ZhLWEyNGRjN2RjZDdjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwMDI5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzRlMjI0YzQ1MmM3NTM0NzcwN2RjMTI3NGRmOTcwYjM2MWQ5ODMwNWNkMzA5YmNkZWU0NDMxZmM1MDQzZjEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Re5GQMOf28nOhU87CBJXQAYZk3qQhGwspSZfLjJfMPE) ppl seem to use this way

that seems like a game-specific thing, so it's out of the scope of this project.

> tho will u ever implement the map dependencies way in fumo_loader

If I'll ever need it myself then I will, but I don't have any plans right now. This loader was made with cs2 in mind, so unless the cs2 ac gets better I won't be implementing new things.
