### ISSUE TITLE
Fail to get driver version

### ISSUE THREAD

**Issue by FlashGordonG** [dumbasPL/fumo_loader#6]
Fail to get driver version
Error code:102
Win32 erroe:1

**Comment by dumbasPL** [comment]
hmm, That's a new one

Please confirm a few things for me:
- Os version (build number)
- Anti-cheats running/installed (please check thoroughly, I've had way too many people claim they don't have anything only to find Faceit, Vanguard, or some other crap)
- Anti-viruses running/installed

Something seems to be blocking the driver from properly initializing, you will have to find out what that thing is.

Keep in mind that this loader is only designed to work against user mode anti-cheats (like VAC) and kernel ones will NEVER be officially supported.

**Comment by FlashGordonG** [comment]
![Uploading 17175125058453463826868070877961.jpg…]()

**Comment by FlashGordonG** [comment]
I don't have any anti virus app  installed even Windows Security Center is removed from the system

**Comment by FlashGordonG** [comment]
What I'm confused is that I don't know what driver was missing

**Comment by mariuszste** [comment]
your image didn't upload, try again.

> What I'm confused is that I don't know what driver was missing

So you have no idea on what this project is and how it works, do you?  
No driver is missing. The driver bundled into this injector is failing to load due to something blocking it. Most likely a kernel anti cheat.

**Comment by dumbasPL** [comment]
your image didn't upload, try again.

> What I'm confused is that I don't know what driver was missing

So you have no idea on what this project is and how it works, do you?  
No driver is missing. The driver bundled into this injector is failing to load due to something blocking it. Most likely a kernel anti cheat.

**Comment by FlashGordonG** [comment]
the image is my OS info Windows 10 Pro
22H2 19045.2546

**Comment by FlashGordonG** [comment]
I checked everything in my task manager  I still don't know what blocked it

**Comment by dumbasPL** [comment]
> I checked everything in my task manager I still don't know what blocked it

Well, neither do I since I don't have access to your system ¯\\\_(ツ)_/¯

If you want me to tell you what it is:
- download [kdu.zip](https://github.com/user-attachments/files/15571532/kdu.zip)
- extract it first (IMPORTANT)
- run diag.bat as admin
- send results here

this will give me everything I need to know and to prove that you're lying about checking "everything"

If you don't trust me, you can build it from the source here: https://github.com/hfiref0x/KDU

**Comment by FlashGordonG** [comment]
so I installed another version of win10 and the problem solved ，it's just os's fault

**Comment by FlashGordonG** [comment]
OS problem
