### ISSUE TITLE
Roblox not supported

### ISSUE THREAD

**Issue by efidemon69** [dumbasPL/fumo_loader#8]
imagine not supporting a game protected by an usermode anti-tamper

**Comment by dumbasPL** [comment]
Hell nah, I'm not installing that crap. Pull requests are welcome if you manage to fix it.

Chances are it's not fumo's fault but the modifications made to the game by the DLL you injected.

**Comment by efidemon69** [comment]
> Hell nah, I'm not installing that crap. Pull requests are welcome if you manage to fix it.
> 
> Chances are it's not fumo's fault but the modifications made to the game by the DLL you injected.

It is fumo's fault, i'm using the same dll i use with my own injector and it does work fine.

**Comment by dumbasPL** [comment]
if you have your own injector then surely you can figure out what's triggering it, right? As I said previously, I'm not downloading this shitty "game". If you have any actually useful information other than "doesn't work" I would be happy to hear it. Contributions welcome.
