### ISSUE TITLE
Not work in Windows 22H2 build 19045.5011

### ISSUE THREAD

**Issue by DevWand** [dumbasPL/fumo_loader#9]
Windows 10 Pro Edition
Version 22H2
Installed on ‎16/‎09/‎2024
OS Build 19045.5011
Windows Feature Experience Pack 1000.19060.1000.0

**Comment by dumbasPL** [comment]
What do you mean by "Not work"? Aby error codes? Steps to reproduce? What DLL? What target? I've used it myself on 22H2 (not sure about the exact build) for a long time without issues. Was it working before? If so, what is the last version you know that it worked on?

Can you please double-check that you don't have anything from the [NOT Compatible with](https://github.com/dumbasPL/fumo_loader?tab=readme-ov-file#limitations) list?

**Comment by dumbasPL** [comment]
check if this is still an issue in https://github.com/dumbasPL/fumo_loader/releases/tag/v1.0.3

closing due to a lack of responses to my previous questions
